################################################
# {{ ansible_managed }}
################################################
#
# This file is managed by Ansible.
# Do not edit this file manually.
# Any changes will be automatically reverted.
#
################################################

# Default Apache virtualhost template

<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot {{ app.doc_root }}
{% set servernames = servername.split() %}
{% for servername in servernames %}
{% if loop.first %}
    ServerName {{ servername }}
{% else %}
    ServerAlias {{ servername }}
{% endif %}
{% endfor %}

    <Directory {{ app.doc_root }}>
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
